Gopkg.lock
Makefile

* adds help messages to all important targets
* prints out commands when invoked
* adds a light green header to each target so it's easier to skim through the logs
* downloads `operator-sdk` binary only if needed (or download not complete) by using `wget -c` flag

chore(make): improves Makefile output

---

README.adoc

Covers basic development setup only.

docs: introduces first cut of README

---

Makefile

e.g. make test args=--focus=telepresence

chore(test): expose args as a list of optional args to ginkgo

---

.travis.yml

fix(travis): removes stage builds

---

Makefile

`DOCKER?=$(if $(or $(in_docker_group),$(is_root)),docker,sudo docker)` was some odd copy-paste which always resulted in calling `sudo docker` for me. That was hanging the build on my machine when performing `docker-push` target.

fix(build): always calls docker from cli (without sudo)

---

cmd/ike/cmd/watch.go
cmd/ike/watch/watch.go
cmd/ike/watch/watch_builder.go
cmd/ike/watch/watch_test.go

Came primarily from improving tests, but might be handy overall.

feat(watch): allows to register multiple handlers

---

Makefile

fix(#78): unifies operator-sdk versions between make and dep

---

cmd/ike/session/session_client.go
pkg/controller/session/session_controller.go
pkg/k8s/deployment_test.go

I can work on a step in CI which would automate that

chore(gofmt): fixes missed formatting

---

.circleci/config.yml

* updates golang to 1.12.4
* updates maistra to 0.10.0

chore(circleci): updates runtime

---

cmd/ike/cmd/develop.go
cmd/ike/cmd/develop_test.go
cmd/ike/session/session.go
cmd/ike/session/session_client.go
cmd/ike/session/session_client_test.go
e2e/infra/test_files.go
e2e/smoke_test.go

feat: enables to run ike against particular namespace

---

cmd/ike/main.go
e2e/smoke_test.go

fix(rand): seeds random generator for "unique" session names

---

pkg/controller/session/model_convert.go
pkg/controller/session/session_controller.go
pkg/istio/destinationrule.go
pkg/istio/destinationrule_test.go
pkg/istio/virtualservice.go
pkg/istio/virtualservice_test.go
pkg/k8s/deployment.go
pkg/k8s/deployment_test.go
pkg/k8s/k8s_suite_test.go
pkg/model/model.go
pkg/openshift/deploymentconfig.go

Fixes #58 
Bonus: godoc and var names cleanup

fix: uses session name for routing

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/PULL_REQUEST_TEMPLATE.md

This PR provides two templates for issues:
And one for the pull request.
Part of #13

github: introduces issues and pr templates

---

.circleci/config.yml

Leverages [CircleCI caching](https://circleci.com/docs/2.0/caching/) to avoid repetitive downloads of dependencies.
- Enhances CircleCI build steps with caching (both regular one and end-to-end tests)
- Adds labels for each step so it's easier to understand what the particular step is responsible for

feat(circleci): caches vendor folder for subsequent builds

---

cmd/ike/session/session.go
cmd/ike/session/session_client.go
e2e/infra/cluster_setup.go
e2e/infra/deployment.go
e2e/infra/pod_state.go
pkg/apis/istio/v1alpha1/register.go
pkg/apis/istio/v1alpha1/session_types.go
pkg/istio/destinationrule.go
pkg/istio/virtualservice.go
pkg/k8s/deployment.go
pkg/openshift/deploymentconfig.go

Adds missing godoc based on https://goreportcard.com/report/github.com/maistra/istio-workspace

chore(godoc): adds missing godocs based on goreportcard

---

.editorconfig
README.adoc
deploy/istio-workspace/crds/istio_v1alpha1_session_cr.yaml
deploy/istio-workspace/role.yaml
deploy/istio-workspace/role_binding.yaml
docs/antora.yml

Ensures consistent formatting of different resources
- `.editorconfig` file with go, yaml and Make conventions
- updates in README

chore: introduces .editorconfig

---

Gopkg.lock
cmd/test-scenario/generators.go
cmd/test-scenario/generators_test.go
pkg/k8s/deployment.go
pkg/k8s/deployment_test.go
pkg/openshift/deploymentconfig.go
pkg/openshift/deploymentconfig_test.go

bug(clone): Remove fields that can cause problems for the cloned proxy

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md

@aslakknutsen This PR will be exceptionally merged w/o the review as you are not available this and coming week. Adding you as a reviewer though so you can see what has been changed.

chore(gh): adds labels to issue templates

---

Makefile

```
[aslak@localhost istio-workspace]$ make help
Usage:
make <target>
Default target (all you need - just run "make")
all                   Runs 'deps format lint test compile' targets
Build
compile               Compiles binaries
test                  Runs tests
clean                 Removes build artifacts
deps                  Fetches all dependencies
format                Removes unneeded imports and formats source code
lint                  Concurrently runs a whole bunch of static analysis tools
codegen               Generates operator-sdk code and bundles packages using go-bindata
Setup
tools                 Installs required go tools
Docker
docker-build          Builds the docker image
docker-push           Pushes docker images to the registry
Istio-workspace operator deployment …
```

chore(make): add environment variables to help

---

pkg/apis/istio/v1alpha1/session_types.go

fix(api): apply correct json tag to inline resource

---

pkg/istio/virtualservice.go
pkg/istio/virtualservice_test.go

fixes #153
This requires some update to the API between Locators and Mutator/Revertors as Subset is missing.

feat(vs): do a better job at setting up the correct route

---

pkg/istio/virtualservice.go
pkg/istio/virtualservice_test.go

feat(scan): scan for more virtual services to mutate

---

pkg/internal/session/session.go
pkg/internal/session/session_client.go

fixes failure on Creating a resource with a resourceVersion set.

fix(develop): allow to join / leave session

---

.circleci/config.yml

build(deps): bumps golang to 1.12.8 patch release

---

e2e/infra/cluster_operations.go
e2e/infra/pod_state.go
e2e/smoke_test.go

Improves diagnostic of e2e test failures.
- dumps logs of all pods in the test namespace
- dumps the state of each container in the pod
- dumps events
Fixes #175

feat: dumps logs for failing e2e tests

---

.golangci.yml
Gopkg.lock
pkg/cmd/format/help_format.go
pkg/controller/session/session_controller.go
pkg/internal/session/session.go
pkg/watch/watch.go
pkg/watch/watch_builder.go
test/cmd/test-scenario/generators.go
test/cmd/test-scenario/main.go
test/ginkgo_custom_reporter.go

GolangCI build check is now failing on new issues.
- tweaks `.golangci.yml` settings
- applies fixes in the code

fix: tunes options for linters

---

.circleci/config.yml
e2e/smoke_test.go
pkg/cmd/config/config.go
pkg/cmd/create/create.go
pkg/cmd/delete/delete.go
pkg/cmd/develop/develop.go
pkg/cmd/develop/develop_test.go
pkg/cmd/root.go
pkg/cmd/watch/watch.go

fix: enables use of IKE_CONFIG env var to pass config file

---

cmd/ike/main.go
e2e/root_cli_test.go

feat(cli): return non 0 exit code on failure

---

Gopkg.lock
pkg/cmd/internal/session/session_func.go
pkg/cmd/internal/session/session_func_test.go
pkg/telepresence/wrapper.go
pkg/telepresence/wrapper_test.go

Follow-up on https://github.com/Maistra/istio-workspace/pull/292#issuecomment-548546146
Related to #284

chore: removes hardcoded tp version

---

pkg/cmd/develop/develop.go

chore: sets current dir while running telepresence

---

Gopkg.lock
pkg/cmd/config/cmd_test.go
pkg/cmd/config/config.go
pkg/cmd/config/config_suite_test.go
pkg/cmd/create/create.go
pkg/cmd/delete/delete.go

feat: supports global envs for config

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md

We forgot to update labels in issue templates :)

fix: updates issue tpl after introducing kind prefix [skip-e2e]

---

Gopkg.lock
pkg/template/template.go
pkg/template/template_test.go

- check if `/spec/template/spec/replicas` exists. Creates if not before patching to `1`
- relaxes test assertion for wrong paths, as error msg changed between the versions of json-patch library
Fixes #341

fix(template): creates replica if not exists

---

pkg/istio/virtualservice.go
pkg/istio/virtualservice_test.go

fix(operator): revert all manipulated virtual service routes

---

docs/modules/ROOT/pages/release_notes.adoc
docs/modules/ROOT/pages/release_notes/release_notes_template.adoc
docs/modules/ROOT/pages/release_notes/v0.0.2.adoc

Fixed few minor things in docs.

chore(docs): cleans up documentation

---

.github/labels.yml

Let's see if the action works :)

fix(gh): improves labels descriptions [skip-e2e]

---

Gopkg.lock
pkg/cmd/version/version.go

Provides `-s|--short` flag for `ike version`
Closes #390

feat(cmd): version cmd prints short semver info [skip-e2e]

---

scripts/release.sh

Minor improvements suggested by shellcheck
- replaces backticks with sub cmd
- checks cmd directly in if
- wraps variables in quotes
- wraps grep pattern in quotes to not be confused with glob

fix(release): improvements in release shell script [skip-e2e]

---

docs/antora.yml
docs/modules/ROOT/pages/release_notes/v0.0.3.adoc

Release v0.0.3

---

.circleci/config.yml

chore(deps): bumps golang to latest release 1.14.3

---

pkg/cmd/develop/develop.go
pkg/cmd/develop/develop_test.go

feat(cli): if no ports are defined, rely on auto expose from tp

---

e2e/e2e_suite_test.go
e2e/error_path_test.go
e2e/infra/cluster_operations.go
e2e/infra/cluster_setup.go
e2e/infra/image_registry.go
e2e/infra/istio_operators_setup.go
e2e/infra/test_service.go
e2e/operator_installation_test.go
e2e/smoke_test.go

Builds and pushes test images before the test suite starts
- cleaned up build / push image logic
- removed unnecessary logins
- minor clean up of infra files
Fixes #313

feat(tests): builds and pushes test images before the test suite starts

---

pkg/cmd/develop/develop.go
pkg/cmd/format/help_format.go

fix(doc): explain passing multi value flags as repeated flags

---

Gopkg.lock

Build against master gave me this so I thought I will share ;) 
Not really sure why it appeared all of the sudden.

chore: updates transitive deps

---

docs/modules/ROOT/pages/contribution_guide.adoc
docs/modules/ROOT/pages/getting_started.adoc

Few minor improvements after skimming through docs.

chore: minor improvements in the docs

---

.circleci/config.yml

chore: bumps golang to 1.15

---

README.adoc
docs/modules/ROOT/pages/index.adoc

docs: adds link to rhd blog

---

pkg/apis/maistra/v1alpha1/session_types.go
pkg/controller/session/model_convert.go
pkg/controller/session/session_controller_int_test.go
pkg/controller/session/session_controller_test.go
pkg/internal/session/session_test.go
pkg/istio/destinationrule.go
pkg/istio/destinationrule_test.go
pkg/istio/gateway.go
pkg/istio/gateway_test.go
pkg/istio/virtualservice.go
pkg/istio/virtualservice_test.go
pkg/istio/virtualservicegateway.go
pkg/model/model.go
test/cmd/test-service/grpc.go
test/cmd/test-service/main.go

Ran analysis in GoLand the other day and fixed a few minor things.
- removes slice preallocs
- removes redundant types
- verifies error occurrence in tests

chore: minor fixes from the linter

---

.circleci/config.yml
.github/labels.yml
.github/workflows/golangci_lint.yml
Makefile
e2e/e2e_suite_test.go
e2e/infra/image_registry.go
e2e/smoke_test.go
pkg/assets/isto-workspace-deploy.go

CircleCI job to build images used by e2e tests
- builds images as separated job
- bumps golang to 1.15.5
- sets host network access for docker builds
Part of #563

feat: introduces new job for building and pushing images

---

.circleci/config.yml
.github/workflows/cleanup_pr_images.yml

fix(ci): uses `latest` tag for master image builds

---

.circleci/config.yml

chore(circle): removes e2e tests job on daily

---

.github/workflows/cleanup_pr_images.yml
.github/workflows/golangci_lint.yml
.github/workflows/release_tag.yml

chore: better names for gh actions

---

docs/modules/ROOT/pages/comparisons/service_preview.adoc

doc: add service preview comparison doc

---

e2e/operator_installation_test.go
pkg/cmd/install/cmd.go

fix(cli): print full url to image being used for install

---

pkg/cmd/execute/cmd.go

fix(cli): watch run command status and log errors

---

.github/workflows/release_pr.yml

fix(release): output the string v of the buffer

---

.github/workflows/release_pr.yml

fix(release): remove newline from rev-parse

---

.github/workflows/release_pr.yml

fix(release): write success status to new commit

---

.github/workflows/release_pr.yml

fix(release): add validation step to /release

---

.github/actions/release.sh
Makefile

`IKE_VERSION` sets explicitly, as tag does not exist yet on the commit for which bundle should be made.
- `release.sh` updates

fix(bundle): sets IKE_VERSION for making bundle

---

pkg/cmd/develop/cmd.go
pkg/cmd/develop/hint.go
pkg/cmd/develop/hint_test.go

feat(cli): print usage hint including exposed hosts

---

config/manager/kustomization.yaml
docs/antora.yml
docs/modules/ROOT/pages/release_notes.adoc
docs/modules/ROOT/pages/release_notes/v0.0.6.adoc

release: highlights of v0.0.6

---

scripts/release/operatorhub.sh

Can't push to community-repository due to the usage of shallow clone.
Don't shallow clone.

Fix shallow clone

---

.circleci/config.yml
.github/workflows/cleanup_pr_images.yml

chore(images): move pr builds to maistra-dev org

---

api/maistra/v1alpha1/session_types.go
config/crd/bases/maistra.io_sessions.yaml
config/manifests/bases/istio-workspace-operator.clusterserviceversion.yaml

Improve the documentation for the OpenAPI description as defined in the CSV.
Add field and improve object documentation
Fixes #641

fix(doc): add better description to the crd

---

config/rbac/kustomization.yaml
config/rbac/leader_election_role_binding.yaml
pkg/cmd/serve/cmd.go

fix(operator): move to use leader election by lease

---

.github/labels.yml

chore(gh): add doc/highlight label

---

pkg/internal/session/session.go

fix(cli): guard against possible nil Route

---

config/manager/kustomization.yaml
docs/antora.yml
docs/modules/ROOT/pages/release_notes.adoc
docs/modules/ROOT/pages/release_notes/v0.0.8.adoc

release: highlights of v0.0.8

---

config/manager/kustomization.yaml
docs/antora.yml
docs/modules/ROOT/pages/release_notes.adoc
docs/modules/ROOT/pages/release_notes/v0.0.9.adoc

release: highlights of v0.0.9

---

go.mod
pkg/log/log.go

fix(operator): set klog to unify loggers

---

config/samples/maistra.io_v1alpha1_session.yaml

fix(bundle): make CSV sample more realistic

---

Makefile

fix(gh-actions): lint-prepare should not compile the code

---

Makefile

fix(infra): run go mod tidy to match dependabot go.sum

---

.golangci.yml
pkg/cmd/config/config.go
pkg/cmd/develop/cmd.go
pkg/cmd/serve/cmd.go
pkg/internal/session/session.go
pkg/istio/virtualservice.go
pkg/reference/enqueue_annotations.go
pkg/telepresence/wrapper.go
pkg/template/template.go
test/matchers/string_matchers.go

fix(lint): enables goerr113

---

.circleci/config.yml
Makefile
integration/tekton/tasks/ike-create/ike-create.yaml
integration/tekton/tasks/ike-delete/ike-delete.yaml
integration/tekton/tasks/ike-session-url/ike-session-url.yaml

0.1 will be parsed to be a float while labels require a string.
"0.1" is parsed as string.

fix(release): add quotes to tekton version in yaml

---

.github/workflows/release_pr.yml
Makefile
scripts/release/release.sh

Add skip-build directive to release commits to speed up process.

fix(release): add skip-build directive to release commits

---

config/manager/manager.yaml
e2e/infra/pod_state.go
e2e/smoke_test.go

The operator container won't start with to low resource restrictions.
Seen when trying to install v0.10.0 on Openshift 4.7.7

fix(operator): increase operator resource limits

---

e2e/smoke_test.go
integration/tekton/tasks/ike-create/ike-create.yaml
integration/tekton/tasks/ike-session-url/ike-session-url.yaml

PR to Tekton Catalog [1] revealed few weak spots in our sh scripts wrapped in Tekton YAML. This PR addresses those findings
- https://github.com/koalaman/shellcheck/wiki/SC2155
- https://github.com/koalaman/shellcheck/wiki/SC2181
[1] https://github.com/tektoncd/catalog/pull/695

fix(tekton): reworks shell scripts to comply with SC

---

Makefile
e2e/error_path_test.go
e2e/smoke_test.go

fix(makefile): executes OC cli only if needed

---

.circleci/config.yml

chore(circleci): uses different account for release images

---

.github/workflows/golangci_lint.yml
.golangci.yml
Makefile
api/maistra/v1alpha1/session_types.go
config/crd/bases/maistra.io_sessions.yaml
pkg/cmd/develop/cmd.go
pkg/cmd/execute/cmd.go
pkg/cmd/format/help_format.go
pkg/log/log.go
pkg/model/model.go
pkg/openshift/deploymentconfig.go
pkg/telepresence/wrapper.go

chore(golint): bumps to 1.40 and enables wrapcheck

---

e2e/smoke_test.go
integration/tekton/tasks/ike-create/ike-create.yaml
integration/tekton/tasks/ike-delete/ike-delete.yaml
integration/tekton/tasks/ike-session-url/ike-session-url.yaml

fix(shellcheck): reworks ike-create task

---

Makefile

fix(make): sets mv with --force flag to avoid prompting

---

controllers/session/conditions.go
controllers/session/session_controller.go
e2e/error_path_test.go
e2e/install_mode_test.go
e2e/smoke_test.go
pkg/internal/session/session.go
pkg/reference/enqueue_annotations.go
pkg/shell/funcs.go
test/cmd/test-service/main.go

Reports successful location of defined reference (source) so that it can be seen in e.g. Openshift Console.
- adds condition when the source ref is located
- moves condition-related to logic to its own file
- minor code cleanups
Fixes #864

feat: adds condition when the source ref is located

---

docs/modules/ROOT/pages/dev_guide.adoc
e2e/infra/cluster_setup.go

Adds section about using `minikube` for local dev/testing.
- documentation update
- minor godoc typo fix

chore(docs): includes section about using minikube for dev

---

.circleci/config.yml
.github/workflows/golangci_lint.yml
.github/workflows/operator_bundle_tests.yml

deps(golang): bumps golang builds to 1.17.3

---

.circleci/config.yml

This will speed-up e2e tests hopefully :)

chore(circleci): bumps e2e machine class to large

---

.github/workflows/release_pr.yml
.github/workflows/release_tag.yml

as v5 introduced breaking changes - https://github.com/octokit/plugin-rest-endpoint-methods.js/releases/tag/v5.0.0

fix(gh-action): updates octokit github package usage

---

Makefile
e2e/install_mode_test.go

see https://github.com/operator-framework/operator-sdk/issues/5946
root cause: https://github.com/operator-framework/operator-registry/issues/992

fix(operator): pins olm image to be aligned with operator-sdk version

---

pkg/cmd/root.go

Ensures `WARN` about the latest release version available (if running an older one) always shows up. Right now if `cmd` had its own `PreRunE` this logic was overwritten. Moving it to `PersistentPreRunE` ensure it's always executed.
- Moves release check logic to `PersistentPreRunE` block of `root` command

fix: ensures version WARN always shows up

---

Makefile
docs/modules/ROOT/pages/cli_reference.adoc
docs/modules/ROOT/pages/contribution_guide.adoc
docs/modules/ROOT/pages/dev_guide.adoc
docs/modules/ROOT/pages/getting_started.adoc
docs/modules/ROOT/pages/integration/tekton/overview.adoc
docs/modules/ROOT/pages/integration/tekton/tasks/ike-create.adoc
docs/modules/ROOT/pages/integration/tekton/tasks/ike-session-url.adoc

Minor fixes from re-reading the docs.

docs: minor improvements of dev docs

---

e2e/error_path_test.go
e2e/infra/cluster_setup.go
e2e/smoke_test.go

- prints controller logs on failure
- dumps session objects from ns on failure

feat(e2e): enriches error logs on test failure
