maistra/istio-workspace

cmd/ike/cmd/develop.go, cmd/ike/main.go
```
Usage:
ike develop [flags]
Flags:
-d, --deployment string   name of the deployment or deployment config
-h, --help                help for develop
-m, --method string       telepresence proxying mode - see https://www.telepresence.io/reference/methods (default "inject-tcp")
-p, --port int            port to be exposed (default 8000)
-r, --run string          command to run your application
```
=> feat(#5): wraps telepresence in ike develop cmd

Makefile, deploy/operator.yaml
* [OpenShift](https://docs.openshift.com/container-platform/3.11/dev_guide/templates.html) template is used to prepare operator object with
image-related variables such as registry, repository, image name and tag
(with defaults)
* Makefile processes the template before deploying operator and passes
relevant key=values (can be overwritten during build e.g.
`IMAGE_TAG=latest make docker-build`)
Closes #7
=> feat(deploy): introduces template for operator

.golangci.yml, Gopkg.lock, cmd/ike/cmd/develop.go, cmd/ike/cmd/root.go, cmd/ike/cmd/version.go, cmd/ike/main.go, pkg/controller/session/session_controller.go
* disallows usage of `github.com/sirupsen/logrus` in favor of `sigs.k8s.io/controller-runtime/pkg/runtime/log`
* disables `gochecknoinits` as both Cobra and operator-sdk relies on
that
* skips autogenerated `./pkg/apis/istio` sources
* disables [gochecknoglobals](https://github.com/leighmcculloch/gochecknoglobals) - probably we should discuss that though
And fixes a bunch of findings too (see commits).
Currently, this runs as part of the default target, so the errors will be caught while running travis build. Ideally, we should move that away to dedicated service - https://golangci.com/. Once we find the final home for this work let's make that happen. WDYT?
=> feat(linter): introduces linter configuration

cmd/ike/cmd/develop.go, cmd/ike/cmd/root.go
* chore(flags): makes flags local for `develop` command - we don't need them persistent as there is no subcommand which would need those values
* chore(cmd): checks tp cmd existence in pre-run hook instead
=> chore(cmd): cleans up cobra flags

.gitignore, Gopkg.lock, Gopkg.toml, Makefile, cmd/ike/cmd/cmd_suite_test.go, cmd/ike/cmd/develop.go, cmd/ike/cmd/develop_test.go, cmd/ike/cmd/root.go, cmd/ike/cmd/version.go, cmd/ike/config/config.go, cmd/ike/main.go, test/cmd.go, test/ginkgo_custom_reporter.go, test/tmp_file.go
* external config sources based on [viper](https://github.com/spf13/viper) (in order of importance)
* flags
* env variables
* config file
* test setup based on [ginkgo](https://github.com/spf13/viper)
* refactored commands to not be singletons
* introduces `config` packages which wraps viper
* centralized settings
* keeping config and flags in sync (so we still can use required flag validation)
Common settings, such as `run` and `build` recipes, could be shared in the repo as a config file rather than being used constantly from the CLI
Fixes #12
=> feat(config): introduces configuration complementary to flags

.travis.yml, Makefile
There's no need to install project tools every time when you run `make` (default target). It's one-off operation when setting up the project or running CI job.
In addition `dep` installation is added to `tools` target so setup is self-contained.
=> chore(make): removes tools from the default target

cmd/ike/cmd/develop.go, cmd/ike/cmd/root.go, cmd/ike/cmd/version.go, test/cmd.go
Instead of using `Run` and regular Cobra hooks, let's start using `RunE` and alike to return errors instead of calling `os.Exit` and let Cobra handle that instead.
This gives us the immediate benefit of better testability - as there's no `os.Exit` in the code under test, there is no risk in abruptly finishing test suite for example.
As-is Cobra will print the usage of the cmd in case of failure. This can be easily disabled by setting `SilenceUsage` flag to `false`. Shall we consider that change too? @aslakknutsen
=> chore(errors): cmds to return errors instead of exiting

Makefile, cmd/ike/cmd/develop.go, cmd/ike/config/config.go
Fixes #26 
* calls `viper.Reset()` when setting up configuration for the command, so tests don't rely on global state. As long as we have a single process (cli) that is fine, but not the ideal solution though - I will think of something better here as it makes testing somewhat brittle.
* redirects outputs to `cobra` command buffers instead - this way we can inspect it while testing (by default it's `Stdout` and `Stderr`)
* runs `ginkgo` in the verbose mode in `make test` target - showing structure of specs
=>  fix(config): flags take precedence over other config sources

Gopkg.lock, cmd/ike/cmd/develop_test.go, test/cmd.go, test/echo/telepresence/main.go, test/tmp_file.go
Adds tests verifying if we pass arguments to `telepresence` correctly.
This is achieved by swapping actual `telepresence` binary with test double - simple executable printing out all the arguments which were passed. That's achieved by Ginko's `gexec.Build` invoked before suite which builds a simple program included in this PR (`test/echo/telepresence/main.go`) and makes it `telepresence` command available in the `$PATH`.
In addition structure of Specs has been slightly changed.
=> test(telepresence): tests proper parameter delegation

Gopkg.lock, Gopkg.toml, cmd/ike/cmd/develop.go
Introduces [`go-cmd`](https://github.com/go-cmd/cmd) instead of relying on `os.exec` Cmd.
* channel-based 
* streaming and buffering output
* real-time status
=> feat(cmd): ports os/exec cmd to go-cmd

.circleci/config.yml
* makes golang version parametrized (and uses 1.12.1)
* makes maistra version parametrized (and uses latest release `v3.11.0+maistra-0.9.0`)
* aligns `kubectl` version with k8s version which maistra cluster is based on
=> chore(ci): updates orbs to 0.0.3

cmd/ike/cmd/session_func_test.go
related to 6c52ea24f3cc450356d761e0712444914cc5e0d6
=> fix(test): Split to new context and check error msg

cmd/ike/cmd/cmd_func.go, e2e/e2e_suite_test.go, e2e/infra/cluster_setup.go, e2e/infra/istio_setup.go, e2e/infra/pod_state.go, e2e/smoke_test.go
Instead of breaking down the command to separate string for each token we can now just pass a string. 
Shortcoming - this does not work for sub-commands, e.g. `docker login -u $(oc whoami)`.
I am working on the docs and aiming for extracting cmd samples from tests directly to the docs so we can have them always up-to-date. That's a first step.
=> chore: allows to use strings for simple cmd

cmd/ike/session/session_suite_test.go, cmd/ike/watch/watch_suite_test.go, cmd/ike/watch/watch_test.go, e2e/infra/istio_setup.go, pkg/controller/session/session_suite_test.go, pkg/istio/istio_suite_test.go, pkg/k8s/deployment.go, pkg/k8s/k8s_suite_test.go, pkg/naming/k8s_naming_suite_test.go, test/test_suite.tpl
I've added goleak when testing watch functionality - helped me finding a few corner cases in this part.
We somehow forgot to add that across the whole test suite.
- adds `AfterSuite` in each `_suite_test.go` with calls to goleak detection
- enhances ginkgo template so that new suites will have that check right from the beginning
=> feat(testing): adds goleak check to each suite and template

cmd/ike/cmd/root.go, cmd/ike/cmd/version.go
Among the cli tools you can find both `cmd --version` and `cmd version` way of getting information about the version of the tool in use. I frequently mix it up so I thought it would be good to actually have both available :)
- adds `--version` flag to root command which only prints version and skips operator start
=> feat: adds --version flag to root cmd

Makefile
Fixes few shortcoming in the `Makefile` discovered while testing new (unreleased) version of `telepresence` with `ike`
- sets TELEPRESENCE_VERSION if not defined by user as env var
- adds timestamp to image-tag/commit when dirty index (so we can re-trigger deployments b/c we always push new image and change the pod spec with it)
- minor: changes label of load-istio target
=> chore: makefile improvements

deploy/istio-workspace/operator.yaml, deploy/istio-workspace/role_binding.yaml
Old, unqualified template api version is `legacy` in openshift, thus I added group `template.openshift.io` instead of plain version.
=> chore: updates apiVersion to fully qualified template group

.golangci.yml
CircleCI started having hiccups with linter. This PR extends deadline (defaults to 1m) to 10m
- `.golangci.yml` deadline settings extended to 10m
=> chore(lint): bumps deadline to unblock CI builds

Gopkg.toml
Without locking deps we can encounter nondeterministic builds, even on `master`.
In addition, this will let us get automated PRs from dependabot to test any new version before we make the update.
- blocks spf13/cobra to latest `v0.0.5`
- blocks spf13/viper to latest `v1.4.0`
=> chore(deps): lock spf13/cobra and viper deps

.circleci/config.yml
Some of the PRs don't need the e2e tests to be executed (i.e. no code changes). For example, docs updates are a good example.
Use with caution though.
- `[skip-e2e]` in the commit message will skip e2e job and mark it as a success.
@aslakknutsen This PR will be exceptionally merged w/o the review as you are not available this and coming week. Adding you as a reviewer though so you can see what has been changed.
=> feat(circle): introduces skip e2e commit directive

README.adoc
The previous link seems to be broken. Linking to the root URL instead.
@aslakknutsen This PR will be exceptionally merged w/o the review as you are not available this and coming week. Adding you as a reviewer though so you can see what has been changed.
=> fix(docs): working link to docs in README

.circleci/config.yml, Makefile
As we have now golangci as separated PR check this will disable linter for CI build on CircleCI.
- explicitly defines the default goal (all)
- introduces `build-ci` target without linter
- switches to `build-ci` for circle-ci builds
- first `compiles` then run `tests` for `all` and `build-ci`
Fixes #157
=> feat(circle): disables linter for ci build

deploy/istio-workspace/operator.yaml, pkg/k8s/deployment.go, pkg/openshift/deploymentconfig.go, pkg/openshift/parser/template_test.go
There's a new version of Telepresence (0.101) out, so we should bump that in our tool.
- default TP version to 0.101
- updates operator template
=> chore: updates Telepresence to latest 0.101

.circleci/config.yml
- bumps golang to 1.12.6 for circle-ci builds
=> chore(circle): updates golang to 1.12.6

.goreleaser.yml, pkg/assets/isto-workspace-deploy.go
Provides initial config for [`goreleaser`](https://github.com/goreleaser/goreleaser).
- cross-compilation for Linux and MacOS (see #159 for the reasons why Windows is not yet supported)
- filtering out certain labels for auto generated changelog.
See #161 #163 #164 for further enhancements.
Fixes #42
=> feat(build): adds goreleaser config for cross-compiling

Makefile
Ongoing version in the built binary will be `latest-tag-next`, so that we know from which stable release it evolved.
=> chore(make): extracts version from git tag

.goreleaser.yml, Makefile, cmd/ike/cmd/install.go, version/version.go
Simplifies versioning and re-use the version in the operator installation process.
- cleaned up versioning scheme
- docker image tag is same as `VERSION` now
- makes `docker-build` rely on `compile` to always build latest binary
- `ike install-operator` uses compile-time defined `version.Version` param to use for template processing if `IKE_IMAGE_TAG` is not defined as env var
Following versioning scheme is proposed. Let's take the following sequence of commits:
`--> a4f --> b5d (tag: v0.0.1) --> cdf --> d56 (tag: v0.0.2) --> 4cb --> ...`
- binary built against `b5d` will have a version `v0.0.1` and it will push docker image tagged with the same
- if there are changes on this commit subsequent builds will be labeled `v0.0.1-dirty-TIMESTAMP`
- build on `cdf` will have `v0.0.1-next` prefix …
=> fix: versioning for operator installer

scripts/release.sh
Sometimes we might want to just see the changes locally without pushing all at once
- `-v|--version` flag to define the released version
- `-d|-dry-run` flag to skip actual push to the repo
- `-h|--help`
- improvements in the arguments validation
=> feat: release dry-run mode

Makefile
Cleans up docker targets and revamps `make help`.
```
╰─ make help
all                          (default) Runs 'deps format lint test compile' targets
build-ci                     Like 'all', but without linter which is executed as separated PR check
clean                        Removes build artifacts
codegen                      Generates operator-sdk code and bundles packages using go-bindata
compile                      Compiles binaries
$(CUR_DIR)/bin/operator-sdk  Downloads operator-sdk cli tool aligned with version defined in Gopkg
deploy-example               Deploys istio-workspace specific resources to defined TEST_NAMESPACE
deploy-operator              Deploys operator resources to defined OPERATOR_NAMESPACE
deploy-test-%                Deploys bookinfo app into defined …
```
=> Makefile docker chores

README.adoc, docs/modules/ROOT/pages/getting_started.adoc, scripts/get.sh, scripts/release.sh
`get.sh` script (inspired by [goreleaser](https://github.com/goreleaser/get/blob/03c4bfde763b30bfe270892ab3ff74949d8e9351/get)). It downloads the binary to the and hints how to add it 
It's purposefully called `get.sh` (which is somewhat generic) instead of `download.sh`, because if we evolve it to the actual installer we still can keep `curl -sL http://git.io/get-ike | bash` snippet. The URL has been created for `get.sh` and there's no way to overwrite it in the future.
- general purpose `get.sh` script which will download latest version of the binary for the given system
- update of docs
- update of README
Fixes #116
=> feat: download script for ike binary

.circleci/config.yml
- bumps golang for circleci to 1.12.7
- introduces re-usable yaml parts for golang (i.e. version in one place)
=> chore(circleci): bumps golang to latest and introduces yaml anchors

.circleci/config.yml, .golangci.yml, .goreleaser.yml, Makefile, README.adoc, docs/modules/ROOT/pages/contribution_guide.adoc
Improves make to always check the presence of required binaries (e.g. `dep`) and assumes that GOPATH has always the first part required and then additional workspaces are added afterward.
- assumes `GOPATH` is appended with custom workspaces
- self-installing binaries - no need to call `make tools`
=> chore(make): gopath fix + self-install

.github/ISSUE_TEMPLATE/bug-report.md, .github/PULL_REQUEST_TEMPLATE.md
There were minor typos in our `.github` templates. 
- Typos in bug-report
- Link to Draft PR GH blog in the PR template
Part of #13
=> fix(github): minor typos in gh templates

.golangci.yml, cmd/ike/main.go
Disables `gofmt` linter as it overlaps with `goimports` which we use as `make format`.
- removes gofmt from linters
- locks the version of golangci-lint (service) to avoid newly introduces linters
Fixes #93
=> chore(linter): disables gofmt

.circleci/config.yml
It seems I missed the version bump in the last PR. Now both binary `build`, `e2e-tests`, and `release` are using the same go version 1.12.7
=> fix(circleci): aligns golang version between jobs

e2e/smoke_test.go
Our e2e tests covered only happy path so far (calling modified service with expected header). We missed verification of official prod route as well as the response from the service prior to modification in developer's route.
- Checks production route
- Checks dev route prior to applying changes
- Minor test code cleanups
Fixes #143
=> test(e2e): verifies production route

Gopkg.lock, pkg/k8s/deployment.go, pkg/k8s/deployment_test.go, pkg/openshift/deploymentconfig.go, pkg/openshift/deploymentconfig_test.go, pkg/template/template.go, pkg/template/template_suite_test.go, pkg/template/template_test.go
Use Go Templates to generate JSON Patch(rfc6902) objects to apply
to the target resource during mutation.
fixes #202
=> feat(template): externalize cloning of target resource

pkg/template/template.go, pkg/template/template_test.go
```
refs:
- name: x
strategy: preparedimage
args:
image: x/x:x
```
fixes #238
=> feat(strategy): support setting up a route for a prepared image

e2e/e2e_suite_test.go, e2e/infra/deployment.go
On 4.x cluster we currently deploy datawire/helloworld based apps for CLI completion tests to `default` namespace. This is wrong and confusing.
- deploys apps to ns created for that purpose
=> fix(test): proper namespaces in cli completion test

Makefile
With new target names being quite excessive we didn't have target - explanation nicely aligned. This PR fixes that.
=> fix: makes padding bigger

.golangci.yml, Gopkg.lock, Makefile
I was preparing golang template repo for future projects and wanted to re-use a bunch of stuff we are having here. Thus I thought having `lint-prepare` target (so some abstraction one can customize) would be helpful. It is used by GolangCI.
=> chore: introduces lint-prepare target

cmd/ike/main.go, test/shell/funcs.go
I guess we shouldn't swallow error thrown from root command :) Seems like left-over from some initial spike.
=> fix: handles error coming from root cmd

.circleci/config.yml, .golangci.yml, Makefile, e2e/bash_completion_test.go, e2e/e2e_suite_test.go, e2e/infra/cluster_operations.go, e2e/infra/istio_operators_setup.go, e2e/infra/test_service.go, e2e/smoke_test.go, test/cmd/test-service/main.go, test/shell/funcs.go
- bumps golang to 1.13.1
- reorganizes e2e tests to avoid duplication of scenario name definition
- adds simple logging to test service
- obtains project dir using a func (removes duplication)
- aligns ocp cli with remote cluster 
- defines cluster version using env var (IKE_CLUSTER_VERSION)
- dumps telepresence log after test failure
**IMPORTANT** This PR disables dc tests until telepresenceio/telepresence/issues/1139 is fixed
=> feat: test infra enhancements

.circleci/config.yml, pkg/cmd/develop/develop.go, pkg/cmd/internal/session/session_func.go, pkg/cmd/internal/session/session_suite_test.go, pkg/telepresence/telepresence_suite_test.go, pkg/telepresence/wrapper.go, pkg/telepresence/wrapper_test.go, pkg/template/template.go, test/echo/main.go, test/shell/test_setup.go
Sends the telepresence version used by the client (i.e. `ike develop`) to the server so the proper version of the image is used. Otherwise, if there's a mismatch, the command will fail highlighting this problem. This happens in the current implementation when we have hardcoded default and we don't send `TELEPRESENCE_VERSION` environment variable in the target deployment.
- checks version of telepresence using binary telepresence version resolution works as follows now:
- `TELEPRESENCE_VERSION` env var takes precedence
- if telepresence binary is available on the path then it will call `telepresence --version`
- otherwise, we return hardcoded default version (last resort)
- introduces telepresence wrapper exposing functionalities used across the
pkgs
- tests tp version passed from the …
=> feat: aligns telepresence version used by client and cluster

pkg/cmd/develop/develop_test.go, pkg/cmd/internal/session/session_func_test.go, pkg/openshift/parser/template_test.go, pkg/telepresence/wrapper_test.go, test/os_env.go
Simplifies overwriting and restoring environment variables in tests.
Now you can simply do:
```golang
It("should process operator template", func() {
// given
envVars := test.TemporaryEnvVars()
envVars.SetAll(map[string]string{
"IKE_DOCKER_REGISTRY":   "quay.io",
"IKE_DOCKER_REPOSITORY": "istio-workspace",
"IKE_IMAGE_NAME":        "ike-cli",
"IKE_IMAGE_TAG":         "latest",
})
defer func() {
envVars.Restore()
}()
// ...
})
```
or by using ginkgo hooks:
```golang
envVars := TemporaryEnvVars()
BeforeEach(func() {
envVars.Set("IKE_DEVELOP_PORT", "4321")
})
AfterEach(envVars.Restore)
```
=> feat: introduces env var handling for tests

e2e/smoke_test.go
Telepresence has been released with a patch so let's enable problematic `DeploymentConfig` tests back.
=> chore: enables deployment config e2e tests

.circleci/config.yml, Gopkg.lock
Updates Golang to the latest release `1.13.4` for CI server.
=> chore(circle): bumps golang to 1.13.4

.circleci/config.yml, pkg/istio/virtualservice.go, pkg/istio/virtualservice_test.go
If a mutation does not occur the original route will be hit and end up
round-robin between different versions.
fixes #307
=> fix(operator): mutate route if subset is missing

.circleci/config.yml
Adds https://github.com/bartoszmajsak/github-changelog-generator as part of `release` job. This will fetch all the PRs since the last release and append it to prepared release notes (some highlights we put in `docs/modules/ROOT/pages/release_notes/VERSION.adoc` as part of release process).
Here's how it looks like https://gist.github.com/bartoszmajsak/a079f411bac1df8b2c560561b3cf7318
- updates `circleci` job to run `ghc` tool to generate release notes for `goreleaser`
Fixes #161
=> feat(circleci): adds changelog integration

.circleci/config.yml
Updates golang runtime to latest `1.13.5`.
- circleci golang version updated both in builder image and e2e test machine
=> chore: bumps golang to latest 1.13.5

Gopkg.toml
`v3.9.0` tag has disappeared from `openshift/api` repo. Locking it down to the commit hash instead.
=> fix(deps): locks openshift api on commit hash

pkg/cmd/root.go, pkg/cmd/serve/serve.go, pkg/cmd/version/version.go
Logs version of the operator in the container logs.
I'm mostly using `k9s` to fiddle around, so I thought it will make my life a bit easier - I know instantly which version I'm running against (especially when using `latest` as image tag)
- logs version when starting operator
- renames `PrintVersion` to `LogVersion`
=> feat: logs version when starting the operator

Gopkg.lock, Gopkg.toml, Makefile, e2e/e2e_suite_test.go
When `ENV_FILE` is set, variables defined in that file will overwrite any other settings (including existing system settings). This way one can have files used for testing against different clusters and swap them easily.
- loads env file before e2e suite starts
=> feat: introduces ENV_FILE var to overwrite variables used in tests

e2e/infra/cluster_operations.go, e2e/infra/istio_operators_setup.go, e2e/infra/test_service.go
Using user defined by `IKE_CLUSTER_USER` variable rather than `oc whoami` command. Latter can retur `kube:admin` which won't work as login to internal docker registry .
=> fix: uses username defined by IKE_CLUSTER_USER instead of oc whoami

e2e/infra/cluster_operations.go
Not sure why it's not failing on `master` build, but locally, having the same version of `golangci-lint` version I was getting this:
```
golangci-lint run
e2e/infra/cluster_operations.go:24: unnecessary leading newline (whitespace)
func LoginAsTestPowerUser() {
make: *** [Makefile:71: lint] Error 1
```
=> chore(lint): removes unnecessary new line

Makefile
Displays env vars with any case and also with spaces before `?=` as part of help output.
=> chore(make): improves grep pattern for env vars [skip-e2e]

docs/modules/ROOT/pages/release_notes/v0.0.2.adoc
Collapsible element is not supported in Antora, as it relies on Asciidoctor 1.x. Collapsible is available in Asciidoctor 2.x. See https://gitlab.com/antora/antora/issues/448#note_198620894
=> fix: reverts old release notes (#371) [skip-e2e]

.circleci/config.yml
- renames e2e jobs to have openshift version in them
- aligns `oc` client version with the remote cluster
=> chore(circle): circle cleanup

.github/labels.yml, .github/workflows/update_labels.yml
Manages github labels as code.
- current actions dumped to yaml file
- github action to be triggered on push on master branch to sync changes
Fixes #13
=> feat(github): introduces label sync action

e2e/infra/test_service.go
To avoid unregistering other already registered members we should
add to the members' array, not just replace it with our new value.
=> fix(e2e): add to the members array instead of replacing it

.golangci.yml, e2e/http_funcs.go, e2e/infra/cluster_operations.go, e2e/infra/istio_operators_setup.go, e2e/smoke_test.go, pkg/cmd/completion/completion.go, pkg/cmd/config/cmd_test.go, pkg/cmd/create/create.go, pkg/cmd/delete/delete.go, pkg/cmd/develop/develop.go, pkg/cmd/install/install.go, pkg/cmd/root.go, pkg/cmd/serve/serve.go, pkg/cmd/version/version.go, pkg/controller/session/model_convert.go, pkg/controller/session/session_controller.go, pkg/controller/session/session_controller_test.go, pkg/internal/session/session.go, pkg/internal/session/session_client.go, pkg/istio/destinationrule.go, pkg/istio/destinationrule_test.go, pkg/istio/virtualservice.go, pkg/istio/virtualservice_test.go, pkg/k8s/deployment.go, pkg/k8s/service.go, pkg/openshift/deploymentconfig.go, test/cmd/test-service/main.go, test/ginkgo_custom_reporter.go, test/shell/test_setup.go, test/tmp_file.go
As we learnt in #378 our usage of golangi-ci linter was a bit wrong. This PR brings order and sanity :)
- fix: disables hugeParam linter
- fix: proper usage of nolint comment
- fix: bypass gocyclo for few functions
- removes unused variable
- adds reasons behind every `//nolint` directive
For example `//nolint[:gosec]` is a wrong syntax (most likely from previous linter we had in place). With this syntax all linter checks are bypassed. The proper syntax is `//nolint:linter1,linter2 //reason explanation`.
Fixes #382
=> fix: cleans up linter usage

README.adoc, docs/modules/ROOT/pages/getting_started.adoc
=> fix(docs): proper install snippet [skip-e2e]

pkg/template/template.go, pkg/template/template_test.go
The target deployment might have configured args and command for the users' image,
however, these make no sense for the telepresence proxy image and might break the startup.
=> fix(operator): remove args and command from telepresence clone

pkg/telepresence/wrapper_test.go
Controls `TELEPRESENCE_VERSION` in dependent tests so that it's wiped out before each one and restored to whatever value it's been set afterwards.
Fixes #389
=> fix(tests): controls tp version env var

.circleci/config.yml
This way we don't have to pollute commit message summary but can simply
include prow-like directive in the comment itself.
Adding `/skip-e2e` anywhere in the commit message will bypass end-to-end tests.
- the new, prow-like syntax for skipping end-to-end tests
- refactored circle check to reusable fragment
=> feat(circle): skips e2e tests when /directive in msg

docs/modules/ROOT/pages/release_notes.adoc
Adding extra line between `include::` directives, so headers are rendered correctly. Currently, this looks as follows:
=> fix(docs): adds extra space between include directives

cmd/ike/main.go, pkg/controller/session/session_controller_int_test.go, pkg/log/log.go, test/cmd/test-service/main.go
Uses JSON only when runs as operator, console encoder otherwise.
- Checks presence of `OPERATOR_NAME` env variable to determine logging format
Fixes #402
=> fix: sets logger based on OPERATOR_NAME env var

README.adoc, docs/modules/ROOT/pages/getting_started.adoc, pkg/cmd/root.go, scripts/get.sh
You can now call `./scripts/get.sh -n ike_v_next` so it will be saved as `ike_v_next`. 
- adds `-n|--name` flag to `get.sh`
- updates README and documentation with installation instruction
- includes output of `./get.sh --help` in docs 
Related to #406
=> feat: ability to specify a file name when using get.sh

.circleci/config.yml, .gitignore
Keeps build files cached (simple file containing content sha) so that when PR is merged to master and there were no other changes in repository redundant builds will be skipped.
- tweaks circle ci jobs by caching build-sha files
Fixes #428
=> feat(ci): caches build results to avoid redundant runs

pkg/cmd/develop/develop.go, pkg/cmd/develop/develop_test.go
Multiple ports can be exosed via cli, config file or env by repeating the flag or
as a comma separated value.
--port 1:2 --port 3:4
IKE_DEVELOP_PORT=1:2,3:4
fixes #45
=> feat(cli): support multiple port expose bindings

README.adoc
`README.adoc` on GH can't render the video tag
/skip-e2e
=> fix(doc): uses thumbnail link instead of video tag

pkg/cmd/create/create.go, pkg/cmd/develop/develop.go, pkg/cmd/internal/session/session_func.go
Basic hint on how to reach the service when header defined in combination with `ike create|develop`
```
Knowing your application url you can now access your new version by using
$ curl -H"x-test-suite:smoke" YOUR_APP_URL.
If you can't see any changes make sure that this header is respected by your app and propagated down the call chain.
```
Fixes #455
=> feat: hints how to reach new service

e2e/infra/test_service.go, e2e/smoke_test.go, pkg/controller/session/session_controller.go, pkg/controller/session/session_controller_int_test.go, pkg/istio/destinationrule.go, pkg/istio/destinationrule_test.go, pkg/istio/gateway.go, pkg/istio/gateway_test.go, pkg/istio/virtualservice.go, pkg/istio/virtualservice_test.go, pkg/istio/virtualservicegateway.go, pkg/istio/virtualservicegatway_test.go, pkg/k8s/deployment.go, pkg/k8s/deployment_test.go, pkg/k8s/service.go, pkg/k8s/service_test.go, pkg/model/model.go, pkg/openshift/deploymentconfig.go, pkg/openshift/deploymentconfig_test.go, test/cmd/test-scenario/generator/modifiers.go, test/cmd/test-scenario/generator/scenarios.go, test/operator/getters.go, test/testclient/getters.go
Add a subdomain host to the gateway which targets a virtual service that auto-add routing headers. 
This allows a user to more easily call into a special route from e.g. a browser.  
fixes #241
=> feat: expose session host route

pkg/apis/istio/v1alpha1/session_types.go, pkg/apis/istio/v1alpha1/zz_generated.deepcopy.go, pkg/controller/session/model_convert.go, pkg/controller/session/model_convert_test.go, pkg/istio/gateway.go, pkg/istio/gateway_test.go, pkg/model/model.go
Allow a client to know which session routes have been exposed for this
session.
fixes #242
=> feat(operator): expose host route in session status

cmd/ike/main.go, pkg/cmd/config/env_vars.go, pkg/cmd/create/create.go, pkg/cmd/delete/delete.go, pkg/cmd/develop/develop.go, pkg/cmd/install/install.go, pkg/cmd/root.go, pkg/cmd/serve/serve.go, pkg/cmd/version/version.go, pkg/cmd/watch/watch.go, pkg/controller/session/session_controller.go, pkg/internal/session/session.go, pkg/log/log.go, pkg/shell/funcs.go, pkg/watch/watch.go, test/cmd/test-service/main.go
Instead of creating a new instance of Logger per subcommand, reuse the single instance
created in main.
Related #240
=> fix(log): use a single instance of Logger

cmd/ike/main.go, pkg/cmd/config/env_vars.go, pkg/cmd/create/create.go, pkg/cmd/delete/delete.go, pkg/cmd/develop/develop.go, pkg/cmd/install/install.go, pkg/cmd/root.go, pkg/cmd/serve/serve.go, pkg/cmd/version/releases.go, pkg/cmd/version/version.go, pkg/cmd/watch/watch.go, pkg/controller/session/session_controller.go, pkg/internal/session/session.go, pkg/internal/session/session_client.go, pkg/log/log.go, pkg/shell/funcs.go, pkg/watch/watch.go, pkg/watch/watch_builder.go
`ike create -i x::z -d reviews-v1 --json`
```json
{
"name": "reviews-v1",
"strategy": "prepared-image",
"args": {
"image": "x::z"
},
"targets": [
{
"kind": "Deployment",
"name": "reviews-v1",
"action": "located",
"labels": {
"app": "reviews",
"version": "v1"
}
},
{
"kind": "Service",
"name": "reviews",
"action": "located",
"labels": {
"app": "reviews"
}
},
{
"kind": "Gateway",
"name": "test-gateway",
"action": "located",
"labels": {
"ike.hosts": "aslak.test.io"
}
}
],
"resources": [
{
"kind": "Deployment",
"name": "reviews-v1-v1-aslak-iphps",
"action": "created"
},
{
"kind": "DestinationRule",
"name": "reviews",
"action": "modified"
},
{
"kind": "Gateway",
"name": "test-gateway",
"action": "modified",
"prop": {
"hosts": "aslak-iphps.aslak.test.io"
}
},
{
"kind": "VirtualService",
"name": …
```
=> fix(cli): return structural response on cli

test/cmd/test-service/propagation.go
The testservice should support to propagate the default header name used
by the operator if no route is given on cli.
=> fix(test): propagate the default route header

Makefile
Moves CSV generation to its own target (`make csv-codegen`) as it will primarily be used during the release (and maybe testing later on). No need to make update of those manifests every single build (`make`) as it happens now
- new Makefile target
=> feat: csv generation in its own target

scripts/get.sh
The get-ike script, when ran without the `--dir` option, doesn't seem to run on my OSX Mojave, and probably also not on Catalina, as it calls `mktemp --suffix`.
Instead of that `mktemp` on OSX takes an option `-t` that defines a prefix for the temporary name:
```
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
mktemp [-d] [-q] [-u] -t prefix
```
This PR tries to fix this by calling `mktemp -t` instead of `mktemp --suffix` on Mac.
Fixes #
=> fix: temp directory creation in get-ike for OSX

docs/modules/ROOT/pages/getting_started.adoc
Fix a typo in the documentation
=> fix(docs): typo in getting-started doc

pkg/k8s/deployment.go, pkg/k8s/deployment_test.go, pkg/model/model.go, pkg/openshift/deploymentconfig.go, pkg/openshift/deploymentconfig_test.go
A strategy to bypass the 'clone' operation. Intended to be used to route
traffic directly to an existing deployment.
Fixes #527
=> feat(operator): add 'existing' strategy

.circleci/config.yml, pkg/internal/session/session.go
In a normal cli setting, we're looking for a Deployment or a DeploymentConfig,
but with the che integration, the Deployment already exists so we need to be
able to wait for something else.
related to #528
=> feat(client): make client wait condition configurable

e2e/infra/image_registry.go, e2e/infra/istio_operators_setup.go, e2e/infra/test_service.go, e2e/operator_installation_test.go
Depending on the tests order it might happen that repo we pull images from points to the wrong one, as it's based on ENV var which we set during the build and test execution from external URL to internal one.
- Sets internal repo before operator tests
=> fix: sets registry to internal before running operator tests

.circleci/config.yml, README.adoc, docs/modules/ROOT/pages/cli_reference.adoc, docs/modules/ROOT/pages/contribution_guide.adoc, docs/modules/ROOT/pages/getting_started.adoc, docs/modules/ROOT/pages/release_notes/v0.0.2.adoc, e2e/bash_completion_test.go, e2e/infra/istio_operators_setup.go, e2e/operator_installation_test.go, pkg/cmd/install/install.go
Renames `ike install-operator` to `ike install`.
- Code changes 
- Docs adjustments
- Fixed version of `microk8s` to `1.18.9`, as `1.19/stable` is now on `1.19.2` causing our setup to fail
Fixes #541
=> Install cmd

.github/workflows/golangci_lint.yml
Error: Unable to process command '::set-env name=GOPATH::/home/runner/work/istio-workspace/istio-workspace/go' successfully.
Error: Unable to process command '::add-path::/home/runner/work/istio-workspace/istio-workspace/go/bin' successfully.
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> fix(test-infra): updates github action commands in linter

e2e/e2e_suite_test.go, e2e/error_path_test.go, e2e/infra/cluster_setup.go, e2e/infra/image_registry.go, e2e/infra/istio_operators_setup.go, e2e/infra/test_service.go, e2e/operator_installation_test.go, e2e/smoke_test.go
Set `PRE_BUILT_IMAGES` to non-empty to control this behavior.
Control where the images are found by setting
* `IKE_INTERNAL_DOCKER_REGISTRY`
* `IKE_EXTERNAL_DOCKER_REGISTRY`
* `IKE_IMAGE_TAG`
* `IKE_DOCKER_REPOSITORY`
* `IKE_IMAGE_NAME`, `IKE_TEST_IMAGE_NAME`, `IKE_TEST_PREPARED_IMAGE_NAME`, `IKE_TEST_PREPARED_NAME`
Fixes #568
=> feat(test-infra): support running test suit on prebuilt images

.github/workflows/cleanup_pr_images.yml
When PR is merged/closed we don't need its images in quay any longer. This action will take care of the cleanup
Related to #563
=> feat(gh-action): cleans up pr images on pr close

Makefile
Cleaned up image build targets. 
- favors podman if available on the `$PATH`
- uses `--no-cache` in case of test images relying on `--build-arg` (see https://github.com/containers/podman/issues/8682)
- does not show `wget` progress to not pollute logs
=> chore(make): fixes image builds targets

.circleci/config.yml, .github/workflows/cleanup_pr_images.yml
Uses branch name extracted from GH PR event on cleanup
- yaml shenanigans
=> fix: refers to PR head ref branch name for image build

.circleci/config.yml, .gitignore
Stores build cache the right way to avoid excessive e2e re-runs (on master ;))
- improved circleci script
Fixes #654
=> fix(circle): tree hash propagates properly to avoid redundant job runs

Makefile
=> chore(make): moves asset generation away from setup section

.circleci/config.yml, .github/actions/release.sh, Makefile, go.mod, tools.go
/skip-e2e
`make bundle` will update `config/manager/kustomization.yaml` with the new v. In theory, this should be committed, but is it really needed as it will be regenerated on each run anyway?
=> release: add bundle push step to release process

.github/actions/release.sh, docs/modules/ROOT/pages/release_notes.adoc
Reworks release notes insertion to the aggregated page by changing the way we use sed
=> fix(docs): inserts release notes placeholder to aggregated page

cmd/ike/main.go
Trying to point the `ike` tool to our k8s cluster running in gcp gave this error:
```
failed to create default client	{"error": "no Auth Provider found for name \"gcp\""}
```
I've found that the `ike` command does not import the `k8s.io/client-go/plugin/pkg/client/auth` package which claims to fix this issue (https://github.com/kubernetes/client-go/issues/242).
I am unsure if where I have added it makes sense for this project so happy to move to a more sensible place! This allows the tool to connect to our cluster successfully.
=> fix(cli): add k8s auth package

.circleci/config.yml
We have alien-ike PGP key with the passphrase and thus we need to handle it in a non-interactive manner on CI.
- adds missing git config for signing commits
- configures custom gpg snippet to be used by git for signing commits
Relates to #491
=> fix(circle): uses custom gpg program to sign commits

.github/workflows/release_pr.yml
`/help` will show possible actions for the release process
- gh action reacting on `/help` comment
- see example here: https://github.com/bartoszmajsak/istio-workspace/pull/53#issuecomment-777784425
=> feat(gh-actions): enables /help cmd for releases

Makefile, config/manager/kustomization.yaml, config/manifests/bases/istio-workspace-operator.clusterserviceversion.yaml, e2e/install_mode_test.go, pkg/cmd/serve/cmd.go
Allow for selecting Multi Namespace install mode in OLM.
Move away from `Namespace`field on Manager and adjust the Cache directly.
Fixes #644
MultiNamespace tests are disabled for now due to https://github.com/operator-framework/operator-sdk/issues/4512
=> feat(operator): support MultiNamespace install mode

test/cmd.go
Conclusion: we won't use logging instead of printing to cmd output as we set our own writer for further inspection while running cmd in tests. In the current solution, we pass buffer which then returns the whole content for further inspection in tests. With logger that would make it a bit more ugly than necessary/
- sets buffer to capture cmd.Err stream as well as Out
Fixes #39
=> chore: sets err buffer to be captured for tests

.github/workflows/release_pr.yml, scripts/release/release.sh
Avoids triggering e2e tests on the automated release related commits
Add /skip-e2e to commit message 
/skip-e2e
=> fix(release): avoid triggering e2e tests on release changes

api/maistra/v1alpha1/session_types.go, api/maistra/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/maistra.io_sessions.yaml, controllers/session/model_convert.go, controllers/session/session_controller.go, controllers/session/session_controller_test.go, pkg/cmd/develop/cmd.go, pkg/internal/session/session.go, pkg/internal/session/session_test.go
If no Route is provided by the Client a default type of route is created. This route is never exposed in the Session object so a client can't know what parameters to use.
Expose the Route used as part of the Session.Status object.
Fixes #691
=> fix(operator): add route to status

PROJECT, api/maistra/v1alpha1/session_types.go, config/manifests/bases/istio-workspace-operator.clusterserviceversion.yaml
Missing CRD description in CSV provided to Operator Hub
Correct the domain vs group naming in PROJECT so Operator SDK correctly joins the data.
Fixes #702
=> feat(operator): add description for crd in csv

config/crd/bases/maistra.io_sessions.yaml, controllers/session/enque_annotations.go, controllers/session/session_controller.go, controllers/session/session_controller_int_test.go, controllers/session/session_controller_test.go, e2e/smoke_test.go, pkg/istio/destinationrule.go, pkg/istio/destinationrule_test.go, pkg/istio/gateway.go, pkg/istio/gateway_test.go, pkg/istio/virtualservice.go, pkg/istio/virtualservice_test.go, pkg/k8s/deployment.go, pkg/k8s/deployment_test.go, pkg/model/model.go, pkg/openshift/deploymentconfig.go, pkg/openshift/deploymentconfig_test.go, pkg/reference/enqueue_annotations.go, pkg/reference/enqueue_annotations_test.go, pkg/reference/reference_suite_test.go
Any of the manipulated Resource can be changed externally at any time and break the Session, either via manual or redeploys scripts etc.
Watch all manipulated Resources for possible change and reconcile if needed.
Fixes #618
=> feat(operator): watch manipulated resources for reconcile on change

docs/modules/ROOT/pages/release_notes/release_notes_template.adoc, docs/modules/ROOT/pages/release_notes/v0.0.5.adoc, docs/modules/ROOT/pages/release_notes/v0.0.6.adoc, docs/modules/ROOT/pages/release_notes/v0.0.7.adoc, docs/modules/ROOT/pages/release_notes/v0.0.8.adoc
related fix: https://github.com/bartoszmajsak/github-changelog-generator/commit/7964493de9c97f91b88cec747a5ba39db007a332 (already released)
/skip-e2e
=> fix: improves readability of section headers in release notes

.circleci/config.yml
Old 16.04 version wasn't even able to `apt-get curl` anymore as repos are unreachable. This PR bumps infra for e2e tests (and release process) to latest supported Ubuntu version.
- bumps executor machine to ubuntu 20.04
- switches asciidoctor from gem to node module (and ensures node 10 is used)
- minor fix for gpg signing as the version update changed behaviour a bit (tty / passthrough options)
- bumps python to 3.9.1
- bumps pandoc to 2.11.4
=> fix(circle): updates executor machine to Ubuntu 20.04

pkg/cmd/root.go, pkg/log/log.go
Cleans up logging and error handling when using `--json` for `ike create`
- general `log.go` cleanup (levels, creation)
- fixes error logging when using `--json` flag
Fixes #739
=> fix: do not ignore errors when outputting in json

pkg/istio/destinationrule_test.go, pkg/istio/virtualservice_test.go, pkg/k8s/deployment_test.go, pkg/model/model.go, pkg/openshift/deploymentconfig_test.go
The version number could be very long so only expose
a short sha version of it in the clone name.
Fixes #683
=> fix(operator): avoid reusing version in clone name

scripts/release/operatorhub.sh, scripts/release/tektoncatalog.sh
=> fix(script): do not require GITHUB_TOKEN in dryRun mode

.circleci/config.yml
Snap has been quite unstable for couple of weeks. This PR brings caching of snaps so they are downloaded once and then shared across the builds.
- downloads snaps locally to install later from files
- caches snaps for each job separately
=> feat(circleci): caches snap deps

scripts/release/operatorhub.sh, scripts/release/tektoncatalog.sh
Fixes the PR creation for Tekton Catalog by introducing OWNER_BASE_BRANCH env var set to `main` and cut the version to `X.Y` for registered tasks.
- `HUB_BASE_BRANCH` defaulted to `master` for operator hub PR automaiton
- `OWNER_BASE_BRANCH` defaulted to `main` for Tekton Catalog
- cuts `X.Y` from `X.Y.Z` semver of operator for tekton tasks.
Fixes #777
=> fix(tekton): ability to define base branch through env var when opening PR

controllers/session/model_convert.go, controllers/session/model_convert_test.go, pkg/istio/destinationrule.go, pkg/istio/gateway.go, pkg/istio/virtualservice.go, pkg/k8s/deployment.go, pkg/model/model.go, pkg/openshift/deploymentconfig.go
Splits action and success state in the model to better reflect the condition / events happening while controller tries to manipulates various resources in the namespace.
Fixes #781
=> feat(operator): split action and success state in model

controllers/session/model_convert_test.go, controllers/session/session_controller_int_test.go, e2e/install_mode_test.go, pkg/istio/destinationrule.go, pkg/istio/destinationrule_test.go, pkg/istio/gateway_test.go, pkg/istio/istio_suite_test.go, pkg/k8s/k8s_suite_test.go, pkg/model/model.go, pkg/reference/enqueue_annotations.go, pkg/template/template_test.go, test/testclient/getters.go
Avoids manipulating the user controlled resources when we don't have to.
- creates new destination rule per host pr session
- deletes on revert
- added multi error handling/reporting
Fixes #796
=> feat(operator): creates new destinationrules instead of manipulating

.github/workflows/release_pr.yml
with `make draft-release-notes VERSION=vX.Y.Z` creating commit `release: highlights of vX.Y.Z` github action now takes version from the PR title and populates it through all the steps. Therefore the process is simplified to invoking commands in the PR comments without a need of duplicating version too.
- github action PR automation scripts
Fixes #794
=> feat(gh-actions): infers version from title

scripts/release/release.sh
All commits prior to `/release` will be squashed to one.
The downside (?): bot account becomes the author of the original commit.
Example of these changes being "tested": https://github.com/bartoszmajsak/istio-workspace/pull/81
- updates in `release.sh` script
Fixes #795
=> feat(gh-actions): squashes pre-release commits

controllers/session/session_controller_test.go, pkg/cmd/serve/cmd.go, pkg/shell/funcs.go, pkg/template/template_test.go, test/cmd/test-service/main.pb.go
Keeping it disabled is a reasonable thing to do as discussed in the related issue.
This PR brings few minor cleanups from going through the findings of this linter.
Fixes #479
=> chore: minor improvements around noglobals linter

pkg/istio/destinationrule.go, pkg/istio/destinationrule_test.go, pkg/istio/gateway.go, pkg/istio/virtualservice.go, pkg/k8s/deployment.go, pkg/k8s/service.go, pkg/model/model.go, pkg/openshift/deploymentconfig.go
Ensure we return an error when no rules found, and when no subset found.
Related to #827
=> fix(error): handle no destination rules found error

pkg/internal/session/session.go, pkg/internal/session/session_test.go, pkg/istio/destinationrule.go, pkg/naming/name_generator.go
Validates given session name against RFC 1123 (which is a standard naming requirement in k8s) and ensures generated one does conform one as well (when the username is used as part of it)
- session name validation if passed from CLI
- changes session name generation to ensure that it conforms to these rules too (especially considering using the username as part of it)
Fixes #832
=> fix(session): makes sure session name follows RFC 1123

cmd/manager/main.go, pkg/cmd/develop/cmd.go, pkg/cmd/develop/cmd_test.go
Ensures that wrapped `ike execute` command passed to `ike develop` is the same binary by expanding its full path based on parent command.
Fixes #829
=> fix: wrapped ike command uses full path of the parent cmd

.github/workflows/cleanup_pr_images.yml, .github/workflows/golangci_lint.yml, .github/workflows/release_pr.yml, .github/workflows/release_tag.yml, .github/workflows/update_labels.yml, .github/workflows/validate_circleci.yml
We were pointing to `ubuntu-latest` which for few months is anyway 20.04, so this change should be harmless (emphasis on should ;).
- updates all the GH-action files
Fixes #671
=> chore(gh-actions): pins ubuntu to ubuntu-20.04

.circleci/config.yml, .gitignore, Makefile
Ginkgo produces one junit xml per suite.
CircleCI can show the test summary but expects one file with all test runs.
This PR introduces simple logic around the build step which takes ginkgo results and merges them into one file, so CircleCI can consume it.
- config for circle
- aggregation using [`junit-report-merger`](https://www.npmjs.com/package/junit-report-merger) node tool \o/
I tried few others (included go and python-based ones but they were not working). This one in the contrary works like a charm.
Another possibility I tried was to use [`gotestsum`](https://github.com/gotestyourself/gotestsum) which is pretty neat but does not really work well with ginkgo. I also tried using `go test` in combination with `gotestsum` to run ginkgo tests, but that somehow ended up with an …
=> feat(circleci): aggregates junit reports for CircleCI

.github/workflows/golangci_lint.yml, Makefile, controllers/session/session_controller_int_test.go
* both locally and in gh action bumped to latest version
* aligned golang version for the action itself
* additionally fixes a little problem found with the new version
=> chore(lint): bumps golangci-lint to latest release

.circleci/config.yml, Makefile
Bumps `operator-sdk` and olm install on microk8s.
- bumps operator-sdk to latest v1.8.1 
- olm-install on microk8s has been updated too because aforementioned issue has been resolved within the container itself
- bumps kustomize to latest release v4.2.0
=> feat(operator): bumps operator-sdk to latest v1.8.1

build/bundle.Containerfile, config/manifests/bases/istio-workspace-operator.clusterserviceversion.yaml, controllers/session/session_controller.go
Missing fields in `oc get`
Calculate fields as we process the refs. 
Fixes #860
=> Populate the missing Status fields RefNames & Strategies

pkg/telepresence/wrapper.go
Minor fix - now showing outup of `telepresence --version` to stdout
Related to #833
=> chore: do not show cmd output when getting tp version

controllers/session/session_controller_int_test.go, controllers/session/validation.go, pkg/model/sync.go, test/cmd/test-scenario/generator/generators.go, test/cmd/test-scenario/generator/scenarios.go
Adds the ability to add custom set of SubGenerators to the scenario generator. Opens up the option to add and remove SubGenerators per scenario.
fixed minor issue where the conditions coming after a failure would all
be false due to variable scope.
=> test: add tests for validation rules

.circleci/config.yml, e2e/smoke_test.go, integration/tekton/tasks/ike-create/ike-create.yaml, integration/tekton/tasks/ike-delete/ike-delete.yaml, integration/tekton/tasks/ike-session-url/ike-session-url.yaml
This PR updates microk8s and istio so we can test against the latest upstream. It also bring few tweaks to Tekton tasks.
- bumps microk8s to 1.22
- bumps tekton to latest release
- auto discovers istio ingress port for tests
- tweaks tekton tasks
=> chore(circleci): bumps microk8s to 1.22

.github/workflows/operator_bundle_tests.yml, Makefile, scripts/release/operatorhub.sh
As operatorhub repository has been split into two locations this affected the ansible-based test harness we use for the release process. This fix corrects the location from where we download it.
This can be further improved when https://github.com/redhat-openshift-ecosystem/operator-test-playbooks/pull/244 is accepted and merged.
- updated test script downloading ansible testing harness from new repository
- new Make target `bundle-test` which will execute tests in `--dry-run` mode
- GitHub Action for testing bundle using newly created target
Fixes #890
=> fix(operatorhub): uses ansible test scripts from new repo

.circleci/config.yml
We don't need to run build nor tests when non-code related assets have been changes such as docs or CI config. This PR fixes it for Circle jobs.
- circleci step to skip job for given commit when only non-code assets have been changed
Fixes #656
=> feat(circleci): skips build and e2e tests for non-code changes

.circleci/config.yml, .github/workflows/operator_bundle_tests.yml, api/maistra/v1alpha1/session_types.go, config/crd/bases/workspace.maistra.io_sessions.yaml, scripts/release/operatorhub/publish.sh, scripts/release/operatorhub/test.sh
Adjusts operator test suite to the same one as used in upstream hub repos.
- fixed test script logic
- narrows test suite (runs `kiwi` instead of `all`)
- adjusts CI config
=> fix(operator): runs the same test suite as on hub PR

Makefile
Before, if `podman` was on the path, it was always using it. Bu if you really want to check how `docker` works, with the current setup you need to manipulate `Makefile`.
- using `IMG_BUILDER` environment variable you can now define desired image builder
=> feat(make): enables image builder overwrite

build/Containerfile, build/ContainerfileTest, build/ContainerfileTestPrepared
Brings updated ubi8-minimal for all our images. This is is due to limitation of @dependabot which handles `Dockerfile`s but still not `Containerfile`s.
- deps update for all images
=> build(deps): Bump ubi8/ubi-minimal from 8.4 to 8.5

docs/modules/ROOT/pages/getting_started.adoc, pkg/cmd/develop/cmd_test.go, pkg/cmd/execute/cmd_test.go, pkg/cmd/internal/session/session_func_test.go, pkg/cmd/internal/session/session_suite_test.go, pkg/shell/funcs.go, pkg/telepresence/wrapper.go, pkg/telepresence/wrapper_test.go, test/shell/test_setup.go, test/tp_stub/main.go
If a newer version of Telepresence is the first one available on path `ike` fails with a misleading error claiming the binary is in the path. It should instead error with information that user should install `v1` instead.
- reworks `telepresence` binary version check
- adjusts tests
Fixes #957
=> fix(tp): handles telepresence version newer than v1

go.mod, go.sum, pkg/cmd/version/releases.go
as this requires code changes (imports) it seems to be out of scope for dependabot
=> build(deps): Bump google/go-github from v32.1.0 to v41.0.0

build/Containerfile, build/ContainerfileTest, build/ContainerfileTestPrepared
Updating our base ubi8 image from 8.5 to 8.6. This resolves all CVEs found in Quay.
- bumps ubi8 images
=> build(deps): bumps ubi8 from 8.5 to 8.6

Makefile, scripts/release/create_release_notes.sh
Moves release notes draft target to its own script. For whatever reason inlined version stopped working :)
- clean up of `Makefile`
- improved script for creating 
Fixes #1013
=> fix(make): extracts release notes generation to script

.circleci/config.yml
Pins olm version to latest v0.21.2 for end-to-end tests.
=> chore(circleci): updates olm version

.goreleaser.yml
Adds configuration for `goreleaser` to build `arm64` binaries so that `ike` can be used on e.g. Mac M1 chips.
- `goreleaser` arm64 config
Fixes #1032
=> feat(build): adds support for ARM64 chips

e2e/bash_completion_test.go, e2e/e2e_suite_test.go, e2e/infra/deployment.go, pkg/k8s/deployment_test.go, pkg/openshift/deploymentconfig_test.go
The previously used `datawire/hello-world` testing image is 102MB. It's a bit too large for the purpose it serves.
- new, slim image for testing autocompletion. 2MB in size
=> chore(e2e): replaces hello-world container with 2MB image

.circleci/config.yml, e2e/infra/pod_state.go, e2e/smoke_test.go, integration/tekton/tasks/ike-create/ike-create.yaml, integration/tekton/tasks/ike-delete/ike-delete.yaml, integration/tekton/tasks/ike-session-url/ike-session-url.yaml
- uses env vars instead of params in the script
- adds missing tekton labels
- e2e-test: ensures tekton-pipelines are installed
=> fix(tekton): improves tekton script by using env vars

pkg/cmd/develop/cmd.go, pkg/telepresence/wrapper.go
Reason for this change is to decouple `develop` command and tp-specific operations.
=> chore(tp): moves tp cmd logic to the wrapper

cmd/ike/main.go, e2e/error_path_test.go, e2e/smoke_test.go, pkg/cmd/develop/cmd.go, pkg/cmd/root.go, pkg/hook/hook.go, pkg/shell/funcs.go, test/cmd.go
Moves shutdown hook logic to a single place and exposes a way to register multiple handlers.
- new `hook` pkg with logic for registering shutdown hooks reacting on `io.Singal`
- small rework of `root` command 
- cmd tests adjustments
=> chore: introduces hook package to handle shutdowns in one place

pkg/cmd/execute/cmd_test.go, pkg/cmd/execute/ike_execute_kill_test.go
Some of the tests, e.g. where shutdown hook is involved, can become flaky. It's evident in slow/constrained environments. Based on my retry runs (`ginkgo run -retry XXXXX`), so not really a scientific method, it seems that increasing timeouts can mitigate the issue. At least it unborked another PR that was struggling with it.
- increases timeouts in tests
=> fix(tests): extends timeouts in command tests

.circleci/config.yml, docs/modules/ROOT/pages/dev_guide.adoc
- docs: defines sections from microk8s
- chore(circle): bumps kubectl to latest 1.22 version
=> docs: re-uses microk8s installation steps from docs

.golangci.yml, Makefile, api/maistra/v1alpha1/session_types.go, config/crd/bases/workspace.maistra.io_sessions.yaml, controllers/session/conditions.go, controllers/session/session_controller.go, controllers/session/validation.go, e2e/e2e_suite_test.go, e2e/error_path_test.go, e2e/gw_in_another_ns_test.go, e2e/infra/cluster_setup.go, e2e/infra/deployment.go, e2e/infra/istio_operators_setup.go, e2e/infra/test_service.go, e2e/install_mode_test.go, e2e/smoke_test.go, pkg/istio/destinationrule.go, pkg/istio/destinationrule_test.go, pkg/istio/gateway.go, pkg/istio/virtualservice.go, pkg/istio/virtualservicegateway.go, pkg/k8s/deployment.go, pkg/model/sync.go, pkg/model/types.go, pkg/openshift/deploymentconfig.go, test/cmd/test-scenario/generator/generators.go, test/cmd/test-scenario/generator/generators_test.go, test/cmd/test-scenario/generator/modifiers.go, test/cmd/test-scenario/generator/scenarios.go, test/cmd/test-scenario/main.go
This change enables routing through Gateway defined in another namespace. It requires cluster-wide or multiple ns operator installations (although the latter seems to be discouraged by operator-sdk due to potential tenancy issues).
In addition, it comes with an e2e test demonstrating such a use case.
What this PR doesn't verify yet is `mesh` gateway special case.
Fixes #1099
=> feat: supports Gateway resource defined in another namespace
